amap:
  #高德 JS API 的 Key，给前端地图页面用，ui/map.html 里加载高德地图底图、地图控件、前端绘制能力
  js_key: ""
  #高德安全密钥，对应前端 JS API 的安全校验
  security_js_code: ""
  #高德 Web Service API 的 Key给 Python 后端请求高德 REST 接口用
  web_service_key: ""，

assistant:
  api_key: ""
